name: Pull Request

on: pull_request

jobs:
  auto-approve-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Dependabot PRs
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: '1 day'
          skip-recent: 1