apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "charts.name" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
{{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlssecret }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ include "charts.name" . }}
          servicePort: 80